import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { HabitatsResponse, HabitType } from '../types';

const gradients: Record<HabitType, string> = {
  grassland: 'from-green-500 to-blue-300',
  forest: 'from-green-600 to-green-300',
  'waters-edge': 'from-green-600 to-blue-200',
  cave: 'from-yellow-900 to-yellow-500',
  mountain: 'from-gray-400 to-blue-300',
  'rough-terrain': 'from-yellow-200 to-blue-200',
  urban: 'from-gray-300 to-gray-600',
  sea: 'from-blue-500 to-blue-200',
  rare: 'from-purple-500 to-purple-200',
};
interface Props {
  data?: HabitatsResponse;
  error?: string | Error;
}

const Home: NextPage<Props> = ({ data, error }: Props) => {
  if (error) {
    return <div>{typeof error === 'string' ? error : error.message}</div>;
  }

  if (data) {
    return (
      <div className="bg-gray-100 h-full py-10">
        <Head>
          <title>Pokemon - next js</title>
          <meta
            name="description"
            content="Pokemon list generated by next js"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="mb-10 text-center text-6xl font-RobotoCondensed">
          Habitats
        </h1>
        <ul className="grid grid-cols-4 gap-4 p-4 max-w-6xl m-auto">
          {data.results.map(({ name }) => (
            <li
              key={name}
              className={`bg-gradient-to-r ${gradients[name]} p-4 justify-center rounded-md text-indigo-900 h-40 flex items-center uppercase font-bold`}
            >
              <Link href={`/habitat/${name}`}>{name}</Link>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  return <div>no data</div>;
};

export default Home;

export const fetchHabitats = async (): Promise<HabitatsResponse> => {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon-habitat');
  return await response.json();
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const data = await fetchHabitats();

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
};
