import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="text-purple-800 bg-gray-500">
      <Head>
        <title>Pokemon - next js</title>
        <meta name="description" content="Pokemon list generated by next js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>start</h1>
    </div>
  );
};

export default Home;
