import type { NextPage } from 'next';
import Head from 'next/head';
import Search from '../components/Search';

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 h-full py-10">
      <Head>
        <title>Pokemon - next js</title>
        <meta name="description" content="Pokemon list generated by next js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mb-10 text-center text-6xl font-RobotoCondensed">
        Next js pokemon
      </h1>
      <Search />
    </div>
  );
};

export default Home;
